#!/usr/bin/env bash
if ! command -v git &> /dev/null; then
    sudo dnf --assumeyes install git
fi

if [ ! -d $HOME/personal ]; then
    mkdir $HOME/personal
fi

git clone https://github.com/haroon-m/dev $HOME/personal/dev

