#!/usr/bin/env bash
dry_run="0"

if [ ! -f $(pwd)/dev_env_marker ]; then
	echo "dev_env_makrer not found"
	echo "navigate to dev repo"
	exit 1
fi

# should be dev
if [ -z "$DEV_ENV" ]; then
    echo "usage: DEV_ENV=\$(pwd) $0 (--dry)"
    exit 1
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    log "copying over files from: $1"
    pushd $1 &>/dev/null
    (
        configs=$(find . -mindepth 1 -maxdepth 1 -type d)
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &>/dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME

# Now is a good time to use age and decrypt files to final location
#copy $DEV_ENV/env/.bashrc $HOME/.bashrc

