#!/usr/bin/env bash

sudo dnf --assumeyes install sway swaybg wofi 
sudo dnf --assumeyes install neovim
sudo dnf --assumeyes install waybar jetbrains-mono-fonts google-noto-sans-mono-fonts fontawesome-fonts pavucontrol


sudo dnf --assumeyes install kitty 
# starship
curl -sS https://starship.rs/install.sh | sh

sudo dnf --assumeyes install age

# Browser
sudo dnf --assumeyes copr enable sneexy/zen-browser
sudo dnf --assumeyes install zen-browser

sudo dnf --assumeyes install NetworkManager NetworkManager-tui NetworkManager-wifi nm-connection-editor nm-applet xdg-desktop-portal-wlr
sudo systemctl enable --now NetworkManager


sudo dnf --assumeyes install tldr fzf btop
sudo dnf --assumeyes install ripgrep

# No sudo pw
u=$(whoami)
echo "$u ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/99_$u > /dev/null
sudo chmod 440 /etc/sudoers.d/99_$u
